services:
  postgres:
    image: postgres:16
    container_name: postgres-bootcamp
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./psql-local:/local

volumes:
  postgres:
    name: postgres
    driver: local
